# Site
title: Less Than Bang
description: A show by and for young and attractive web people.
author: "Tom Ashworth & Paul Adam Davis"
author_email: tom@phuu.net
base: http://localhost:4001/
permalink: /:categories/:title
date_format: "%A, %d %B %Y"

# Development
auto: true
server: true
server_port: 4001

# Jekyll
markdown: rdiscount
exclude: [node_modules, less, grunt.js, Gruntfile, package.json, README.md, CNAME]
safe: false